name: Build-Test
run-name: Fast-Api Docker build and test
env:
  DOCKER_IMAGE_NAME: fast-api-bike-daily:0.0.2
  REGISTRY: antonisst
on:
  push:
    branches:
      - main  # The default branch name in your repository
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker
        run: docker build . -t $DOCKER_IMAGE_NAME

      - name: Run Docker
        run: docker run -d -p 8000:8000 $DOCKER_IMAGE_NAME

      - name: Wait for the server to start
        run: sleep 6  

      - name: install dev requirements to run pytest
        run: pip install -r dev-requirements.txt

      - name: Test container with pytest
        run: pytest ./
      
  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{env.REGISTRY}} / ${{env.DOCKER_IMAGE_NAME}}

          